"""Bittensor subnet economics tracker."""
from __future__ import annotations
import httpx
from typing import Any
from .opportunity import Opportunity, estimate_qdw_fit

TIMEOUT = httpx.Timeout(15.0)

# ── Known subnet economics (from research) ─────────────────────────────────

SUBNET_ECONOMICS = {
    118: {
        "name": "Ditto",
        "description": "Agent-memory harness — Docker artifact, validators run it",
        "artifact": "docker_memory_harness",
        "gpu_required": False,
        "reward_topology": "TOP_K",
        "paying_slots": 5,
        "reward_split": "65/14/10/7/4",
        "miner_pool_tao_day": 34.16,
        "evaluation_fee_tao": 0.04,
        "evaluation_fee_usd": 7.70,
        "ip_terms": "Platform-owned on reward-earning win",
        "local_evaluator": True,
        "github": "https://github.com/ditto-assistant/ditto-subnet",
        "qdw_fit": 0.96,
        "recommendation": "ATTACK",
    },
    11: {
        "name": "TrajectoryRL",
        "description": "Open skill factory — SKILL.md packs in real sandboxes",
        "artifact": "SKILL.md",
        "gpu_required": False,
        "reward_topology": "WINNER_TAKE_ALL",
        "paying_slots": 1,
        "miner_pool_tao_day": 0,  # unknown
        "evaluation_fee_tao": 0.44,
        "evaluation_fee_usd": 84.48,
        "ip_terms": "Copyright transfers on reward-earning win",
        "local_evaluator": True,
        "github": "https://github.com/trajectoryRL/trajectoryRL",
        "qdw_fit": 0.94,
        "recommendation": "INVESTIGATE",
    },
    62: {
        "name": "Ridges",
        "description": "Autonomous SWE agent — agent.py submitted",
        "artifact": "agent.py",
        "gpu_required": False,
        "reward_topology": "WINNER_TAKE_ALL",
        "paying_slots": 1,
        "miner_pool_tao_day": 40.33,
        "evaluation_fee_tao": 0,
        "evaluation_fee_usd": 0,
        "ip_terms": "IP irrevocably assigned to Hidden Harvest Ventures",
        "local_evaluator": True,
        "upload_credits": True,
        "github": "https://github.com/ridgesai/ridges",
        "qdw_fit": 0.92,
        "recommendation": "INVESTIGATE",
    },
    61: {
        "name": "RedTeam",
        "description": "Rotating authorized programming/security challenges",
        "artifact": "solution_code",
        "gpu_required": "8GB server",
        "reward_topology": "PROPORTIONAL",
        "paying_slots": 10,
        "miner_pool_tao_day": 26.44,
        "evaluation_fee_tao": 0,
        "evaluation_fee_usd": 0,
        "ip_terms": "Retained by miner",
        "local_evaluator": False,
        "docs": "https://docs.theredteam.io",
        "qdw_fit": 0.72,
        "recommendation": "INVESTIGATE",
    },
    56: {
        "name": "Gradients",
        "description": "Training code repos — validators provide GPUs",
        "artifact": "training_repo",
        "gpu_required": False,
        "reward_topology": "TOP_2_PER_TOURNAMENT",
        "paying_slots": 2,
        "miner_pool_tao_day": 54.29,
        "evaluation_fee_tao": 0.25,
        "evaluation_fee_usd": 48.00,
        "ip_terms": "Retained by miner",
        "local_evaluator": False,
        "qdw_fit": 0.88,
        "recommendation": "ATTACK",
    },
    15: {
        "name": "ORO",
        "description": "Shopping agent evaluation on real commerce tasks",
        "artifact": "agent",
        "gpu_required": False,
        "reward_topology": "KING_OF_HILL",
        "paying_slots": 1,
        "miner_pool_tao_day": 0,
        "evaluation_fee_tao": 0,
        "evaluation_fee_usd": 0,
        "ip_terms": "Unknown",
        "local_evaluator": False,
        "qdw_fit": 0.65,
        "recommendation": "MONITOR",
    },
    60: {
        "name": "BitSec",
        "description": "Vulnerability-finding AI agent benchmark",
        "artifact": "vulnerability_agent",
        "gpu_required": False,
        "reward_topology": "WINNER_TAKE_ALL",
        "paying_slots": 1,
        "miner_pool_tao_day": 0.148,
        "evaluation_fee_tao": 0,
        "evaluation_fee_usd": 0,
        "ip_terms": "Public after rounds",
        "local_evaluator": False,
        "docs": "https://docs.bitsec.ai",
        "qdw_fit": 0.60,
        "recommendation": "MONITOR",
    },
    34: {
        "name": "BitMind/GAS",
        "description": "AI-generated-content detection — submit models",
        "artifact": "detection_model",
        "gpu_required": False,
        "reward_topology": "ACCURACY_BASED",
        "paying_slots": 5,
        "miner_pool_tao_day": 0,
        "evaluation_fee_tao": 0,
        "evaluation_fee_usd": 0,
        "ip_terms": "Unknown",
        "local_evaluator": False,
        "github": "https://github.com/BitMind-AI/bitmind-subnet",
        "qdw_fit": 0.45,
        "recommendation": "MONITOR",
    },
}


async def fetch_subnet_economics(tao_price: float) -> list[Opportunity]:
    """Convert known subnet economics to Opportunities."""
    opportunities = []
    for netuid, info in SUBNET_ECONOMICS.items():
        opp = Opportunity(
            kind="subnet",
            title=f"SN{netuid} {info['name']}: {info['description']}",
            sponsor=info["name"],
            discovered_at="",
            reward_type="token_emission",
            amount_min_usd=info["evaluation_fee_usd"] * -1 if info["evaluation_fee_usd"] else 0,
            amount_max_usd=info["miner_pool_tao_day"] * tao_price if info["miner_pool_tao_day"] else 0,
            reward_confidence=0.7 if info["miner_pool_tao_day"] else 0.3,
            artifact_type=info["artifact"],
            hardware=info["gpu_required"] if info["gpu_required"] else None,
            ip_assignment=info.get("ip_terms"),
            submission_fee=f"{info['evaluation_fee_tao']} TAO" if info["evaluation_fee_tao"] else None,
            reuse_score=info["qdw_fit"],
            estimated_engineering_hours=20 if info["qdw_fit"] > 0.8 else 40,
            local_evaluator_available=info.get("local_evaluator", False),
            factory_candidate=info["name"].lower(),
            existing_assets=["qdw", "gitgoblin", "qdw-workbench"],
            cash_at_risk=info["evaluation_fee_usd"],
            expected_value_confidence="MEDIUM" if info["miner_pool_tao_day"] else "LOW",
            paying_slots=info["paying_slots"],
            source="bittensor_research",
            source_url=info.get("github", info.get("docs", "")),
            source_data=info,
            rating="A" if info["qdw_fit"] > 0.85 else "B" if info["qdw_fit"] > 0.6 else "C",
            recommendation=info["recommendation"],
        )
        opportunities.append(opp)
    return opportunities
